### ISSUE TITLE
This code not run

### ISSUE THREAD

**Issue by jmoyaseg** [CiscoSE/AddMerakiMXL3FirewallRuleToNetworks#1]
Hi,
The code does not work. When I run it it gives the following error:

**Traceback (most recent call last):
  File "j:\Randstad\Meraki\00_Scripts Phyton\AddMerakiMXL3FirewallRuleToNetworks-master\AddRulesToMXL3Firewall.py", line 103, in <module>
    myNetworks = meraki.getnetworklist(config.meraki_api_key, config.meraki_org_id, None, True)
AttributeError: module 'meraki' has no attribute 'getnetworklist'**

Is normal??
Regards

**Comment by jasmah** [comment]
Hi,

We have updated the code wtih the latest Meraki SDK.  Please gve it a try and let us know if it is working for you now.  Thank you.  Jason

**Comment by jmoyaseg** [comment]
Hi Jason,
The code fails when it checks for a rule named "Default rule" on line 156.

The error is:
AddRulesToMXL3Firewall.py", line 156, in <module>
    if theRule["comment"]!="Default rule":
TypeError: string indices must be integers

Thanks for the effort
Javi
